### ISSUE TITLE
Error: Command "url" is already defined!

### ISSUE THREAD

**Issue by d-koppenhagen** [webdriverio/webdriverrtc#1]
I got an error by running webdriverrtc.

```
/Users/me/git/wonder_2.0/node_modules/webdriverio/lib/webdriverio.js:257
                throw new ErrorHandler.RuntimeError('Command "' + fnName + '" 
                      ^
Error: Command "url" is already defined!
    at new ErrorHandler.RuntimeError (/Users/me/git/wonder_2.0/node_modules/webdriverio/lib/utils/ErrorHandler.js:92:12)
    at Object.client.addCommand (/Users/me/git/wonder_2.0/node_modules/webdriverio/lib/webdriverio.js:257:23)
    at Object.client.addCommand (/Users/me/git/wonder_2.0/node_modules/webdriverio/lib/multibrowser.js:174:25)
    at new WebdriverRTC (/Users/me/git/wonder_2.0/node_modules/webdriverrtc/lib/webdriverrtc.js:52:19)
    at Object.module.exports.init (/Users/me/git/wonder_2.0/node_modules/webdriverrtc/lib/webdriverrtc.js:62:12)
    at Object.<anonymous> (/Users/dannyk/git/wonder_2.0/webrtcTest.js:45:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

any suggestions?

**Comment by christian-bromann** [comment]
I haven't ported webdriverrtc yet to use WebdriverIOv3, you need WebdriverIO with sha1 of 07542b0a1e83fc0e805a8c63368bc608a84ec114

I know it's no where documented but I hope it will work soon with the current version of webdriverio

**Comment by d-koppenhagen** [comment]
Thanks for your fast answer, I will try it.

**Comment by ledancs** [comment]
Hi @christian-bromann,
I tried to run the examples and I get the same error as @d-koppenhagen even after using the latest version in the repository. Is this a difficult bug to fix?
Thanks a lot!

**Comment by christian-bromann** [comment]
@ledancs you need the WebdriverIO version at sha 07542b0a1e83fc0e805a8c63368bc608a84ec114

**Comment by ledancs** [comment]
@christian-bromann I was not aware of this link:
https://travis-ci.org/webdriverio/webdriverio/jobs/65410471
I will give it a go later. Thanks a lot!

**Comment by lail3344** [comment]
@christian-bromann  even i changed the dependency to 07542b0a1e83fc0e805a8c63368bc608a84ec114, webdriverrtc still not work with below error message:
webdriverrtc/node_modules/webdriverio/node_modules/chainit/index.js:167
    to.__addToChain(fnName, fn);
       ^

TypeError: to.__addToChain is not a function
    at Function.add (/home/luq/Dev2/my_github/webdriverrtc/node_modules/webdriverio/node_modules/chainit/index.js:167:8)
    at null.<anonymous> (/home/luq/Dev2/my_github/webdriverrtc/node_modules/webdriverio/lib/utils/PromiseHandler.js:99:17)
    at Multibrowser.instance.startAnalyzing (/home/luq/Dev2/my_github/webdriverrtc/lib/webdriverrtc.js:44:40)
    at Object.<anonymous> (/home/luq/Dev2/my_github/webdriverrtc/examples/getstats.demo.js:54:6)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)

**Comment by lail3344** [comment]
Ok, i got it partial work by changing dependency to v2.5.0rc1 and fixs the include error report from lib/multibrowser.js in line4(./multibrowser/Instance -> ./multibrowser/instance)

But, it still had problem in calculate the result,

{ transport: 'udp',
  local: 
   { candidateType: 'local',
     ipAddress: '10.239.10.28',
     port: '57983' },
  remote: 
   { candidateType: 'local',
     ipAddress: '10.239.10.28',
     port: '39085' } }

/home/luq/Dev2/webdriverrtc/lib/helpers/calcResult.js:18
        Object.keys(results).forEach(function(attr) {
               ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at Object.module.exports.+ (/home/luq/Dev2/webdriverrtc/lib/helpers/calcResult.js:18:16)
    at /home/luq/Dev2/webdriverrtc/lib/helpers/calcResult.js:25:39
    at Array.forEach (native)
    at Object.module.exports.+ (/home/luq/Dev2/webdriverrtc/lib/helpers/calcResult.js:18:30)
    at /home/luq/Dev2/webdriverrtc/lib/helpers/calcResult.js:25:39
    at Array.forEach (native)
    at Object.module.exports.+ (/home/luq/Dev2/webdriverrtc/lib/helpers/calcResult.js:18:30)
    at /home/luq/Dev2/webdriverrtc/lib/helpers/calcResult.js:13:32
    at Array.forEach (native)

**Comment by gougou9903** [comment]
I am getting the same error when I run the getstats.demo.js. Does anybody know how to change the WebdriverIO version to sha 07542b0a1e83fc0e805a8c63368bc608a84ec114?
